version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Varun@123   # Root password
      MYSQL_DATABASE: weatherdb        # Initial database
    ports:
      - "3307:3306"  # Host port
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/weatherdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Varun@123
    depends_on:
      - mysql
    restart: unless-stopped

  frontend:
    build: ./app-weather-react-main
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  mysql-data:
